name: Sync-To-Coding
on:
  schedule:
    - cron: '34 1-23/4 * * *'
  workflow_dispatch:
jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git init
          git remote add origin https://github.com/andadmadm/buckup.git
          git fetch --all
          git push --all --force coding
          git push --tags --force coding
          git remote add origin https://e.coding.net/bkca5/buckup/buckup.git
          git push -u origin master
          git show-ref # useful for debugging
          git branch --verbose
          # publish all
